### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Riya28042000** [Isvisoft/flutter_screen_recording#32]
Gives the error Shutting down VM and FATAL EXCEPTION: main

**Comment by Riya28042000** [comment]
I/System.out(15265): Scaled Density
I/System.out(15265): 2.75
I/System.out(15265): Original Resolution
I/System.out(15265): 1080 x 2030
I/System.out(15265): Calcule Resolution
I/System.out(15265): 680 x 1280
D/AndroidRuntime(15265): Shutting down VM
E/AndroidRuntime(15265): FATAL EXCEPTION: main
E/AndroidRuntime(15265): Process: com.example.pdf, PID: 15265
E/AndroidRuntime(15265): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=333, result=-1, data=Intent { (has extras) }} to activity {com.example.pdf/com.example.pdf.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property _result has not been initialized
E/AndroidRuntime(15265):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4335)
E/AndroidRuntime(15265):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4379)
E/AndroidRuntime(15265):        at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime(15265):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
E/AndroidRuntime(15265):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15265):        at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(15265):        at android.app.ActivityThread.main(ActivityThread.java:6651)
E/AndroidRuntime(15265):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15265):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(15265):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
E/AndroidRuntime(15265): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property _result has not been initialized
E/AndroidRuntime(15265):        at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:68)
E/AndroidRuntime(15265):        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(15265):        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(15265):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(15265):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(15265):        at android.app.Activity.dispatchActivityResult(Activity.java:7355)
E/AndroidRuntime(15265):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4331)
E/AndroidRuntime(15265):        ... 9 more
Lost connection to device.
I/Process (15265): Sending signal. PID: 15265 SIG: 9
