### ISSUE TITLE
Flutter: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

### ISSUE THREAD

**Issue by abdullah432** [Isvisoft/flutter_screen_recording#44]
Andriod Q, need a Foreground service request now. Please make this update. I'm about to publish my application to playstore but due to this issue, I'm not able to.
Exception in Android Q (10)

```
compileSdkVersion 29
targetSdkVersion 29
```
I know after downgrading to compileSdkVersion 28. The app will work but then I will not be able to upload it to the play store.

```
D/AndroidRuntime( 5005): Shutting down VM
E/AndroidRuntime( 5005): FATAL EXCEPTION: main
E/AndroidRuntime( 5005): Process: com.example.screenrecordtest, PID: 5005
E/AndroidRuntime( 5005): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=333, result=-1, data=Intent { (has extras) }} to activity {com.example.screenrecordtest/com.example.screenrecordtest.MainActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 5005):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
E/AndroidRuntime( 5005):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
E/AndroidRuntime( 5005):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 5005):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 5005):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 5005):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 5005):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5005):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 5005):        at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 5005):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5005):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 5005):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 5005): Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 5005):        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
E/AndroidRuntime( 5005):        at android.os.Parcel.createException(Parcel.java:2357)
E/AndroidRuntime( 5005):        at android.os.Parcel.readException(Parcel.java:2340)
E/AndroidRuntime( 5005):        at android.os.Parcel.readException(Parcel.java:2282)
E/AndroidRuntime( 5005):        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime( 5005):        at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
E/AndroidRuntime( 5005):        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)        
E/AndroidRuntime( 5005):        at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:66)
E/AndroidRuntime( 5005):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime( 5005):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime( 5005):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:652)
E/AndroidRuntime( 5005):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:618)
E/AndroidRuntime( 5005):        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
E/AndroidRuntime( 5005):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
E/AndroidRuntime( 5005):        ... 11 more
E/AndroidRuntime( 5005): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 5005):        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:479)
E/AndroidRuntime( 5005):        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime( 5005):        at android.os.Binder.execTransactInternal(Binder.java:1154)
E/AndroidRuntime( 5005):        at android.os.Binder.execTransact(Binder.java:1123)
E/AndroidRuntime( 5005):
I/Process ( 5005): Sending signal. PID: 5005 SIG: 9
```

**Comment by salime45** [comment]
This plugin use https://pub.dev/packages/flutter_foreground_plugin for that. You have to follow the instruccions and add the configuration to your AndroidManifest

**Comment by abdullah432** [comment]
Thanks for replying. I know that and i add the configuration to my AndroidManifest but still app crash when click on start record button in compileSdkVersion 29 and targetSdkVersion 29. I checked your example too which is running  compileSdkVersion 28 and targetSdkVersion 28, please change it to 29 and see by your self.

**Comment by abdullah432** [comment]
Please reopen the issue until it is fixed.

**Comment by abdullah432** [comment]
After adding this line, `android:foregroundServiceType="mediaProjection" ` now it's working.
Add it here: `<service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService" android:foregroundServiceType="mediaProjection"/>`
AndroidManefist.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	package="com.kukustudio.textcrawler">
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-sdk
		android:minSdkVersion="23"
		tools:overrideLibrary="changjoopark.com.flutter_foreground_plugin" />
	<application
        android:label="Star Crawler"
        android:icon="@mipmap/launcher_icon">
		<activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
			<!--
			Specifies an Android theme to apply to this Activity as soon as
			the Android process has started. This theme is visible to the user
			while the Flutter UI initializes. After that, this theme continues
			to determine the Window background behind the Flutter UI.
			-->
			<meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
			<!--
			Displays an Android View that continues showing the launch screen
			Drawable until Flutter paints its first frame, then this splash
			screen fades out. A splash screen is useful to avoid any visual
			gap between the end of Android's launch screen and the painting of
			Flutter's first frame.
			-->
			<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
        <service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService" android:foregroundServiceType="mediaProjection"/>
		<!--
		Don't delete the meta-data below.
		This is used by the Flutter tool to generate GeneratedPluginRegistrant.java
		-->
		<meta-data android:name="flutterEmbedding" android:value="2" />
	</application>
</manifest>

```

**Comment by abdullah432** [comment]
You made a great plugin but documentation should include these settings. It's so frustrating. It takes me more than 3 days to finally make it work. Thanks for the plugin.

**Comment by ifananomali** [comment]
> After adding this line, `android:foregroundServiceType="mediaProjection" ` now it's working.
> Add it here: `<service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService" android:foregroundServiceType="mediaProjection"/>`
> AndroidManefist.xml
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> 	xmlns:tools="http://schemas.android.com/tools"
> 	package="com.kukustudio.textcrawler">
> 	<uses-permission android:name="android.permission.WAKE_LOCK" />
> 	<uses-sdk
> 		android:minSdkVersion="23"
> 		tools:overrideLibrary="changjoopark.com.flutter_foreground_plugin" />
> 	<application
>         android:label="Star Crawler"
>         android:icon="@mipmap/launcher_icon">
> 		<activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
> 			
> 			<meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
> 			
> 			<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
> 			<intent-filter>
> 				<action android:name="android.intent.action.MAIN" />
> 				<category android:name="android.intent.category.LAUNCHER" />
> 			</intent-filter>
> 		</activity>
>         <service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService" android:foregroundServiceType="mediaProjection"/>
> 		
> 		<meta-data android:name="flutterEmbedding" android:value="2" />
> 	</application>
> </manifest>
> ```

Thank you for helping, I got this problem too

**Comment by deepak-ariceum** [comment]
Is it working for everyone?
I have the exact same things, but it's not working for me. Please let me know. 
Gives me the below error,
```
 java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 5654):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
E/AndroidRuntime( 5654):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
E/AndroidRuntime( 5654):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 5654):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 5654):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 5654):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
E/AndroidRuntime( 5654):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 5654):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 5654):        at android.app.ActivityThread.main(ActivityThread.java:7807)
E/AndroidRuntime( 5654):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5654):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 5654):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
E/AndroidRuntime( 5654): Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 5654):        at android.os.Parcel.createException(Parcel.java:2088)
E/AndroidRuntime( 5654):        at android.os.Parcel.readException(Parcel.java:2056)
E/AndroidRuntime( 5654):        at android.os.Parcel.readException(Parcel.java:2004)
E/AndroidRuntime( 5654):        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime( 5654):        at android.media.projection.MediaProjection.<init>(MediaProjection.java:68)
E/AndroidRuntime( 5654):        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:147)
E/AndroidRuntime( 5654):        at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:63)
E/AndroidRuntime( 5654):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime( 5654):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime( 5654):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:802)
E/AndroidRuntime( 5654):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime( 5654):        at android.app.Activity.dispatchActivityResult(Activity.java:8292)
E/AndroidRuntime( 5654):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
E/AndroidRuntime( 5654):        ... 11 more
E/AndroidRuntime( 5654): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 5654):        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:501)
E/AndroidRuntime( 5654):        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime( 5654):        at android.os.Binder.execTransactInternal(Binder.java:1021)
E/AndroidRuntime( 5654):        at android.os.Binder.execTransact(Binder.java:994)

```

**Comment by adigujjar** [comment]
@deepak-ariceum 
use this one in latest version
<service
           android:name="com.foregroundservice.ForegroundService"
           android:foregroundServiceType="mediaProjection">
       </service>  
       
       instead of 
       
               <service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService" android:foregroundServiceType="mediaProjection"/>
