### ISSUE TITLE
Unhandled exception ( attempt to invokde virtual method startActivityForResult() on NULL )

### ISSUE THREAD

**Issue by cs-mtahir** [Isvisoft/flutter_screen_recording#6]
I am using   **flutter_screen_recording: ^1.0.1** for flutter screen recording application , but i am getting the following exception by calling `FlutterScreenRecording.startRecordScreen` , any help ?

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void android.app.Activity.startActivityForResult(android.content.Intent, int, android.os.Bundle)' on a null object reference, null)
E/flutter (20318): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (20318): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (20318): <asynchronous suspension>
E/flutter (20318): #2      FlutterScreenRecording.startRecordScreen (package:flutter_screen_recording/flutter_screen_recording.dart:15:40)
E/flutter (20318): #3      _MyAppState.startScreenRecord (package:flutter_recording/main.dart:101:48)
E/flutter (20318): #4      _MyAppState.build.<anonymous closure> (package:flutter_recording/main.dart:90:15)
E/flutter (20318): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (20318): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (20318): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (20318): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (20318): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (20318): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (20318): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (20318): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (20318): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (20318): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (20318): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (20318): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (20318): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (20318): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (20318): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (20318): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (20318): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (20318): #22     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (20318): #23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (20318): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (20318): #25     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (20318): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```

**Comment by salime45** [comment]
use the last version
